<?php

namespace Database\Seeders;

use App\Models\witel;
use App\Models\sto;
use Illuminate\Database\Seeder;

class StoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public static function run()
    {
        sto::insert([
            ['witel_id' => StoSeeder::findWitel('DENPASAR'), 'nama_sto' => 'KUTA'],
            ['witel_id' => StoSeeder::findWitel('DENPASAR'), 'nama_sto' => 'NUSA DUA'],
            ['witel_id' => StoSeeder::findWitel('DENPASAR'), 'nama_sto' => 'BENOA'],
            ['witel_id' => StoSeeder::findWitel('DENPASAR'), 'nama_sto' => 'SEMINYAK'],
            ['witel_id' => StoSeeder::findWitel('DENPASAR'), 'nama_sto' => 'TOHPATI'],
            ['witel_id' => StoSeeder::findWitel('DENPASAR'), 'nama_sto' => 'SANUR'],
            ['witel_id' => StoSeeder::findWitel('DENPASAR'), 'nama_sto' => 'UBUNG'],
            ['witel_id' => StoSeeder::findWitel('DENPASAR'), 'nama_sto' => 'SUKAWATI'],
            ['witel_id' => StoSeeder::findWitel('DENPASAR'), 'nama_sto' => 'MONANG MANING'],
            ['witel_id' => StoSeeder::findWitel('DENPASAR'), 'nama_sto' => 'KALIASEM A'],
            ['witel_id' => StoSeeder::findWitel('DENPASAR'), 'nama_sto' => 'JIMBARAN'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'SEMPOLAN'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'SUKOSARI'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'KALISAT'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'GENTENG'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'JEMBER'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'BONDOWOSO'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'SITUBONDO'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'MUNCAR'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'PESANGGARAN'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'KETAPANG'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'ROGOJAMPI'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'KALIBARU'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'BESUKI'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'MLANDINGAN'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'ASEMBAGUS'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'BENCULUK'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'BANYUWANGI'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'GLENMORE'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'JEMBER'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'WONGSOREJO'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'DURENAN'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'TRENGGALEK'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'KANDANGAN PARE'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'BLITAR'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'NGANJUK'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'NGUNUT'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'PRIGI'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'WARUJAYENG'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'CAMPUR DARAT'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'NGADILUWIH'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'BINANGUN'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'WATES KEDIRI'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'TULUNGAGUNG'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'PRAMBON'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'KERTOSONO'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'KEDIRI'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'GURAH'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'MOJOROTO'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'LODOYO'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'PENATARAN'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'SRENGAT'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'WLINGI'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'KESAMBEN'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'SAMBI'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'PARE'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'PAPAR'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'GONDANG'],
            ['witel_id' => StoSeeder::findWitel('KEDIRI'), 'nama_sto' => 'KALIDAWIR'],
            ['witel_id' => StoSeeder::findWitel('NTT'), 'nama_sto' => 'BETUN'],
            ['witel_id' => StoSeeder::findWitel('NTT'), 'nama_sto' => 'MAUMERE'],
            ['witel_id' => StoSeeder::findWitel('NTT'), 'nama_sto' => 'ATAMBUA A'],
            ['witel_id' => StoSeeder::findWitel('NTT'), 'nama_sto' => 'NIKI-NIKI'],
            ['witel_id' => StoSeeder::findWitel('NTT'), 'nama_sto' => 'SEBA'],
            ['witel_id' => StoSeeder::findWitel('NTT'), 'nama_sto' => 'WOLO WARU'],
            ['witel_id' => StoSeeder::findWitel('NTT'), 'nama_sto' => 'REO'],
            ['witel_id' => StoSeeder::findWitel('NTT'), 'nama_sto' => 'OESAPA'],
            ['witel_id' => StoSeeder::findWitel('NTT'), 'nama_sto' => 'WAIKABUBAK'],
            ['witel_id' => StoSeeder::findWitel('NTT'), 'nama_sto' => 'WAINGAPU'],
            ['witel_id' => StoSeeder::findWitel('NTT'), 'nama_sto' => 'RUTENG'],
            ['witel_id' => StoSeeder::findWitel('NTT'), 'nama_sto' => 'TENAU'],
            ['witel_id' => StoSeeder::findWitel('NTT'), 'nama_sto' => 'KUPANG'],
            ['witel_id' => StoSeeder::findWitel('NTT'), 'nama_sto' => 'ENDE'],
            ['witel_id' => StoSeeder::findWitel('NTT'), 'nama_sto' => 'LARANTUKA'],
            ['witel_id' => StoSeeder::findWitel('NTT'), 'nama_sto' => 'LABUHAN BAJO'],
            ['witel_id' => StoSeeder::findWitel('NTT'), 'nama_sto' => 'KALABAHI'],
            ['witel_id' => StoSeeder::findWitel('NTT'), 'nama_sto' => 'SOE'],
            ['witel_id' => StoSeeder::findWitel('NTT'), 'nama_sto' => 'KEFAMENANU'],
            ['witel_id' => StoSeeder::findWitel('NTT'), 'nama_sto' => 'BAJAWA'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'GORANGGARENG'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'JENANGAN'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'SARANGAN'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'MAGETAN'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'PULUNG'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'PONOROGO'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'PACITAN'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'SLAHUNG'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'SAMBIT'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'KALITIDU'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'UTERAN'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'JOGOROGO'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'RENGEL'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'SUMBERREJO'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'PUNUNG'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'BOJONEGORO'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'MERAKURAK'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'KARANGJATI'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'NGAWI'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'MAOSPATI'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'LOROG'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'MADIUN'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'CARUBAN'],
            ['witel_id' => StoSeeder::findWitel('MADURA'), 'nama_sto' => 'GAYAM / SAPUDI'],
            ['witel_id' => StoSeeder::findWitel('MADURA'), 'nama_sto' => 'SAPEKAN'],
            ['witel_id' => StoSeeder::findWitel('MADURA'), 'nama_sto' => 'OMBEN'],
            ['witel_id' => StoSeeder::findWitel('MADURA'), 'nama_sto' => 'PAMEKASAN'],
            ['witel_id' => StoSeeder::findWitel('MADURA'), 'nama_sto' => 'KETAPANG'],
            ['witel_id' => StoSeeder::findWitel('MADURA'), 'nama_sto' => 'BATANGATANG'],
            ['witel_id' => StoSeeder::findWitel('MADURA'), 'nama_sto' => 'SAMPANG'],
            ['witel_id' => StoSeeder::findWitel('MADURA'), 'nama_sto' => 'PRAGAAN'],
            ['witel_id' => StoSeeder::findWitel('MADURA'), 'nama_sto' => 'AMBUNTEN'],
            ['witel_id' => StoSeeder::findWitel('MADURA'), 'nama_sto' => 'SUMENEP'],
            ['witel_id' => StoSeeder::findWitel('MALANG'), 'nama_sto' => 'SINGOSARI'],
            ['witel_id' => StoSeeder::findWitel('MALANG'), 'nama_sto' => 'GONDANGLEGI'],
            ['witel_id' => StoSeeder::findWitel('MALANG'), 'nama_sto' => 'GADANG'],
            ['witel_id' => StoSeeder::findWitel('MALANG'), 'nama_sto' => 'AMPELGADING'],
            ['witel_id' => StoSeeder::findWitel('MALANG'), 'nama_sto' => 'MALANG'],
            ['witel_id' => StoSeeder::findWitel('MALANG'), 'nama_sto' => 'TUMPANG'],
            ['witel_id' => StoSeeder::findWitel('MALANG'), 'nama_sto' => 'GUNUNG KAWI'],
            ['witel_id' => StoSeeder::findWitel('MALANG'), 'nama_sto' => 'LAWANG'],
            ['witel_id' => StoSeeder::findWitel('MALANG'), 'nama_sto' => 'TUREN'],
            ['witel_id' => StoSeeder::findWitel('MALANG'), 'nama_sto' => 'DONOMULYO'],
            ['witel_id' => StoSeeder::findWitel('MALANG'), 'nama_sto' => 'SUMBER MANJING'],
            ['witel_id' => StoSeeder::findWitel('MALANG'), 'nama_sto' => 'NGANTANG'],
            ['witel_id' => StoSeeder::findWitel('MALANG'), 'nama_sto' => 'BATU'],
            ['witel_id' => StoSeeder::findWitel('MALANG'), 'nama_sto' => 'BANTUR'],
            ['witel_id' => StoSeeder::findWitel('MALANG'), 'nama_sto' => 'DAMPIT'],
            ['witel_id' => StoSeeder::findWitel('MALANG'), 'nama_sto' => 'PAGAK'],
            ['witel_id' => StoSeeder::findWitel('MALANG'), 'nama_sto' => 'KARANGPLOSO'],
            ['witel_id' => StoSeeder::findWitel('MALANG'), 'nama_sto' => 'PAKIS'],
            ['witel_id' => StoSeeder::findWitel('MALANG'), 'nama_sto' => 'SAWOJAJAR'],
            ['witel_id' => StoSeeder::findWitel('MALANG'), 'nama_sto' => 'BLIMBING'],
            ['witel_id' => StoSeeder::findWitel('MALANG'), 'nama_sto' => 'BURING'],
            ['witel_id' => StoSeeder::findWitel('MALANG'), 'nama_sto' => 'KLOJEN'],
            ['witel_id' => StoSeeder::findWitel('MALANG'), 'nama_sto' => 'KEPANJEN'],
            ['witel_id' => StoSeeder::findWitel('MALANG'), 'nama_sto' => 'SUMBERPUCUNG'],
            ['witel_id' => StoSeeder::findWitel('MATARAM'), 'nama_sto' => 'SILA'],
            ['witel_id' => StoSeeder::findWitel('MATARAM'), 'nama_sto' => 'ALAS'],
            ['witel_id' => StoSeeder::findWitel('MATARAM'), 'nama_sto' => 'MATARAM A'],
            ['witel_id' => StoSeeder::findWitel('MATARAM'), 'nama_sto' => 'SELONG'],
            ['witel_id' => StoSeeder::findWitel('MATARAM'), 'nama_sto' => 'GERUNG'],
            ['witel_id' => StoSeeder::findWitel('MATARAM'), 'nama_sto' => 'SWETA'],
            ['witel_id' => StoSeeder::findWitel('MATARAM'), 'nama_sto' => 'TENTE'],
            ['witel_id' => StoSeeder::findWitel('MATARAM'), 'nama_sto' => 'DOMPU'],
            ['witel_id' => StoSeeder::findWitel('MATARAM'), 'nama_sto' => 'SAPE'],
            ['witel_id' => StoSeeder::findWitel('MATARAM'), 'nama_sto' => 'BIMA'],
            ['witel_id' => StoSeeder::findWitel('MATARAM'), 'nama_sto' => 'PRAYA'],
            ['witel_id' => StoSeeder::findWitel('MATARAM'), 'nama_sto' => 'MASBAGIK'],
            ['witel_id' => StoSeeder::findWitel('MATARAM'), 'nama_sto' => 'MALUK'],
            ['witel_id' => StoSeeder::findWitel('MATARAM'), 'nama_sto' => 'TALIWANG'],
            ['witel_id' => StoSeeder::findWitel('MATARAM'), 'nama_sto' => 'SENGGIGI'],
            ['witel_id' => StoSeeder::findWitel('MATARAM'), 'nama_sto' => 'SUMBAWA BESAR'],
            ['witel_id' => StoSeeder::findWitel('MATARAM'), 'nama_sto' => 'EMPANG'],
            ['witel_id' => StoSeeder::findWitel('MATARAM'), 'nama_sto' => 'KEMPO'],
            ['witel_id' => StoSeeder::findWitel('PASURUAN'), 'nama_sto' => 'GENDING'],
            ['witel_id' => StoSeeder::findWitel('PASURUAN'), 'nama_sto' => 'LUMAJANG'],
            ['witel_id' => StoSeeder::findWitel('PASURUAN'), 'nama_sto' => 'PROBOLINGGO'],
            ['witel_id' => StoSeeder::findWitel('PASURUAN'), 'nama_sto' => 'TONGAS'],
            ['witel_id' => StoSeeder::findWitel('PASURUAN'), 'nama_sto' => 'SUKAPURA'],
            ['witel_id' => StoSeeder::findWitel('PASURUAN'), 'nama_sto' => 'BANGIL'],
            ['witel_id' => StoSeeder::findWitel('PASURUAN'), 'nama_sto' => 'KRAKSAAN'],
            ['witel_id' => StoSeeder::findWitel('PASURUAN'), 'nama_sto' => 'PASURUAN'],
            ['witel_id' => StoSeeder::findWitel('PASURUAN'), 'nama_sto' => 'GONDANG WETAN'],
            ['witel_id' => StoSeeder::findWitel('PASURUAN'), 'nama_sto' => 'GRATI'],
            ['witel_id' => StoSeeder::findWitel('PASURUAN'), 'nama_sto' => 'LECES'],
            ['witel_id' => StoSeeder::findWitel('PASURUAN'), 'nama_sto' => 'TOSARI'],
            ['witel_id' => StoSeeder::findWitel('PASURUAN'), 'nama_sto' => 'PAITON'],
            ['witel_id' => StoSeeder::findWitel('PASURUAN'), 'nama_sto' => 'JATIROTO'],
            ['witel_id' => StoSeeder::findWitel('PASURUAN'), 'nama_sto' => 'NONGKO JAJAR'],
            ['witel_id' => StoSeeder::findWitel('SIDOARJO'), 'nama_sto' => 'MOJOSARI'],
            ['witel_id' => StoSeeder::findWitel('SIDOARJO'), 'nama_sto' => 'PRIGEN'],
            ['witel_id' => StoSeeder::findWitel('SIDOARJO'), 'nama_sto' => 'GEMPOL'],
            ['witel_id' => StoSeeder::findWitel('SIDOARJO'), 'nama_sto' => 'PLOSO'],
            ['witel_id' => StoSeeder::findWitel('SIDOARJO'), 'nama_sto' => 'NGORO JOMBANG'],
            ['witel_id' => StoSeeder::findWitel('SIDOARJO'), 'nama_sto' => 'MLIRIP MOJOKERTO'],
            ['witel_id' => StoSeeder::findWitel('SIDOARJO'), 'nama_sto' => 'DLANGGU'],
            ['witel_id' => StoSeeder::findWitel('SIDOARJO'), 'nama_sto' => 'SEPANJANG'],
            ['witel_id' => StoSeeder::findWitel('SIDOARJO'), 'nama_sto' => 'JOMBANG'],
            ['witel_id' => StoSeeder::findWitel('SIDOARJO'), 'nama_sto' => 'PANDAAN'],
            ['witel_id' => StoSeeder::findWitel('SIDOARJO'), 'nama_sto' => 'TULANGAN'],
            ['witel_id' => StoSeeder::findWitel('SIDOARJO'), 'nama_sto' => 'SIDOARJO'],
            ['witel_id' => StoSeeder::findWitel('SIDOARJO'), 'nama_sto' => 'BEJI'],
            ['witel_id' => StoSeeder::findWitel('SIDOARJO'), 'nama_sto' => 'MOJOKERTO'],
            ['witel_id' => StoSeeder::findWitel('SIDOARJO'), 'nama_sto' => 'GEDANGAN'],
            ['witel_id' => StoSeeder::findWitel('SIDOARJO'), 'nama_sto' => 'PURWOSARI'],
            ['witel_id' => StoSeeder::findWitel('SIDOARJO'), 'nama_sto' => 'KRIAN'],
            ['witel_id' => StoSeeder::findWitel('SIDOARJO'), 'nama_sto' => 'NGORO INDUSTRI'],
            ['witel_id' => StoSeeder::findWitel('SIDOARJO'), 'nama_sto' => 'SUKODONO'],
            ['witel_id' => StoSeeder::findWitel('SIDOARJO'), 'nama_sto' => 'MOJOAGUNG'],
            ['witel_id' => StoSeeder::findWitel('SIDOARJO'), 'nama_sto' => 'PACET'],
            ['witel_id' => StoSeeder::findWitel('SINGARAJA'), 'nama_sto' => 'AMLAPURA'],
            ['witel_id' => StoSeeder::findWitel('SINGARAJA'), 'nama_sto' => 'NEGARA'],
            ['witel_id' => StoSeeder::findWitel('SINGARAJA'), 'nama_sto' => 'UBUD'],
            ['witel_id' => StoSeeder::findWitel('SINGARAJA'), 'nama_sto' => 'GILIMANUK'],
            ['witel_id' => StoSeeder::findWitel('SINGARAJA'), 'nama_sto' => 'LOVINA'],
            ['witel_id' => StoSeeder::findWitel('SINGARAJA'), 'nama_sto' => 'BANGLI'],
            ['witel_id' => StoSeeder::findWitel('SINGARAJA'), 'nama_sto' => 'PUPUAN'],
            ['witel_id' => StoSeeder::findWitel('SINGARAJA'), 'nama_sto' => 'SINGARAJA'],
            ['witel_id' => StoSeeder::findWitel('SINGARAJA'), 'nama_sto' => 'CANDIDASA'],
            ['witel_id' => StoSeeder::findWitel('SINGARAJA'), 'nama_sto' => 'TAMPAK SIRING'],
            ['witel_id' => StoSeeder::findWitel('SINGARAJA'), 'nama_sto' => 'GIANYAR'],
            ['witel_id' => StoSeeder::findWitel('SINGARAJA'), 'nama_sto' => 'SEMARAPURA'],
            ['witel_id' => StoSeeder::findWitel('SINGARAJA'), 'nama_sto' => 'SERIRIT'],
            ['witel_id' => StoSeeder::findWitel('SINGARAJA'), 'nama_sto' => 'BATURITI'],
            ['witel_id' => StoSeeder::findWitel('SINGARAJA'), 'nama_sto' => 'TABANAN'],
            ['witel_id' => StoSeeder::findWitel('SINGARAJA'), 'nama_sto' => 'KINTAMANI'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA SELATAN'), 'nama_sto' => 'DARMO'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA SELATAN'), 'nama_sto' => 'RUNGKUT'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA SELATAN'), 'nama_sto' => 'WARU II TROPODO'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA SELATAN'), 'nama_sto' => 'JAGIR'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA SELATAN'), 'nama_sto' => 'GUBENG'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA SELATAN'), 'nama_sto' => 'WARU'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA SELATAN'), 'nama_sto' => 'MANYAR'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA SELATAN'), 'nama_sto' => 'INJOKO'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA UTARA'), 'nama_sto' => 'KEBALEN'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA UTARA'), 'nama_sto' => 'SEDAYU'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA UTARA'), 'nama_sto' => 'TANDES'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA UTARA'), 'nama_sto' => 'KAPASAN'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA UTARA'), 'nama_sto' => 'KANDANGAN'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA UTARA'), 'nama_sto' => 'BAMBE'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA UTARA'), 'nama_sto' => 'GRESIK'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA UTARA'), 'nama_sto' => 'KALIANAK'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA UTARA'), 'nama_sto' => 'KENJERAN'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA UTARA'), 'nama_sto' => 'SANGKAPURA / BAWEAN'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA UTARA'), 'nama_sto' => 'LAKARSANTRI'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA UTARA'), 'nama_sto' => 'BRONDONG'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA UTARA'), 'nama_sto' => 'TANJUNG PERAK'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA UTARA'), 'nama_sto' => 'BALONGPANGGANG'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA UTARA'), 'nama_sto' => 'KEDAMEAN'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA UTARA'), 'nama_sto' => 'LAMONGAN'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA UTARA'), 'nama_sto' => 'CERME'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA UTARA'), 'nama_sto' => 'BABAD'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA UTARA'), 'nama_sto' => 'DUDUK SAMPEYAN'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA UTARA'), 'nama_sto' => 'MERGOYOSO'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA UTARA'), 'nama_sto' => 'SUKODADI'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA UTARA'), 'nama_sto' => 'KARANGPILANG'],
            ['witel_id' => StoSeeder::findWitel('PASURUAN'), 'nama_sto' => 'YOSOWILANGUN'],
            ['witel_id' => StoSeeder::findWitel('PASURUAN'), 'nama_sto' => 'PASIRIAN'],
            ['witel_id' => StoSeeder::findWitel('PASURUAN'), 'nama_sto' => 'TEMPEH'],
            ['witel_id' => StoSeeder::findWitel('PASURUAN'), 'nama_sto' => 'KLAKAH'],
            ['witel_id' => StoSeeder::findWitel('PASURUAN'), 'nama_sto' => 'SENDURO'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'AMBULU'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'ARJASA'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'BALUNG'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'JENGGAWAH'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'KENCONG'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'PRAJEKAN'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'PUGER'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'RAMBIPUJI'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'SUKOWONO'],
            ['witel_id' => StoSeeder::findWitel('JEMBER'), 'nama_sto' => 'TANGGUL'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'TUBAN'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'SUMOROTO'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'BANCAR'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'KEREK'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'JATI ROGO'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'PADANGAN'],
            ['witel_id' => StoSeeder::findWitel('MADURA'), 'nama_sto' => 'WARU PAMEKASAN'],
            ['witel_id' => StoSeeder::findWitel('MADURA'), 'nama_sto' => 'ARJASA PAMEKASAN'],
            ['witel_id' => StoSeeder::findWitel('NTT'), 'nama_sto' => 'LEWOLEBA'],
            ['witel_id' => StoSeeder::findWitel('SURABAYA UTARA'), 'nama_sto' => 'PONGANGAN'],
            ['witel_id' => StoSeeder::findWitel('MADURA'), 'nama_sto' => 'BANGKALAN'],
            ['witel_id' => StoSeeder::findWitel('MADURA'), 'nama_sto' => 'TANJUNG BUMI'],
            ['witel_id' => StoSeeder::findWitel('MADURA'), 'nama_sto' => 'KAMAL'],
            ['witel_id' => StoSeeder::findWitel('MADURA'), 'nama_sto' => 'AROSBAYA'],
            ['witel_id' => StoSeeder::findWitel('MADIUN'), 'nama_sto' => 'WALIKUKUN'],
            ['witel_id' => StoSeeder::findWitel('MADURA'), 'nama_sto' => 'BLEGA'],
            ['witel_id' => StoSeeder::findWitel('NTT'), 'nama_sto' => 'BAA (Kab.ROTE)'],
            ['witel_id' => StoSeeder::findWitel('MADURA'), 'nama_sto' => 'MASALEMBO'],
        ]);
    }

    public static function findWitel($namaWitel){
        return witel::where('nama_witel', '=', $namaWitel)->first()->id;
    }
}
